# Generated by Django 4.1.7 on 2023-03-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='textur/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='files',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='files',
            field=models.ManyToManyField(blank=True, to='housemodels.filemodel'),
        ),
    ]
