# Generated by Django 4.1.7 on 2023-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0002_filemodel_remove_mymodel_files_mymodel_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='textures',
            field=models.FileField(default=False, upload_to='models/textures', verbose_name='Текстуры для модели'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='files',
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='files',
            field=models.FileField(default=False, upload_to='models', verbose_name='модель здания'),
            preserve_default=False,
        ),
    ]
