# Generated by Django 4.1.7 on 2023-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0003_mymodel_textures_remove_mymodel_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textures', models.FileField(upload_to='models/textures', verbose_name='Текстуры для модели')),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='textures',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='textures',
            field=models.ManyToManyField(to='housemodels.textures'),
        ),
    ]
