# Generated by Django 4.1.7 on 2023-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0004_textures_remove_mymodel_textures_mymodel_textures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='files',
            field=models.ImageField(upload_to='models', verbose_name='модель здания'),
        ),
    ]
