# Generated by Django 4.1.7 on 2023-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0006_alter_mymodel_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binn', models.FileField(upload_to='models/textures', verbose_name='bin-файлы')),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='files',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='gltf',
            field=models.FileField(default=False, upload_to='models', verbose_name='gltf-файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='binn',
            field=models.ManyToManyField(to='housemodels.bin'),
        ),
    ]
