# Generated by Django 4.1.7 on 2023-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0007_bin_remove_mymodel_files_mymodel_gltf_mymodel_binn'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='img',
            field=models.ImageField(default=False, upload_to='', verbose_name='Фото карточки, размер 250*200 px'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bin',
            name='binn',
            field=models.FileField(upload_to='models', verbose_name='bin-файлы'),
        ),
    ]
