# Generated by Django 4.1.7 on 2023-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0009_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Номер телефона для связи'),
        ),
    ]
