# Generated by Django 4.1.7 on 2023-03-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0010_alter_application_name_alter_application_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('question', models.TextField(verbose_name='Ваш вопрос')),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='bin',
            options={'verbose_name': 'bin-файлы', 'verbose_name_plural': 'bin-файлы'},
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name': 'Карточки многоэтажных зданий', 'verbose_name_plural': 'Карточки многоэтажных зданий'},
        ),
        migrations.AlterModelOptions(
            name='textures',
            options={'verbose_name': 'Текстуры', 'verbose_name_plural': 'Текстуры'},
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
