# Generated by Django 4.1.7 on 2023-03-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0011_feedback_alter_application_options_alter_bin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
