# Generated by Django 4.1.7 on 2023-04-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemodels', '0013_feedback_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='models/layout', verbose_name='Планировка здания')),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='layout',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='housemodels.layout', verbose_name='Планировка здания'),
            preserve_default=False,
        ),
    ]
